# blocklist
branches:
  except:
  - develop
  - experimental
language: java
sudo: false
script: mvn clean package
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)